# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

asymmetric_checkerboard_mass <- function(X, Y, resolution1, resolution2) {
    .Call(`_RDM_asymmetric_checkerboard_mass`, X, Y, resolution1, resolution2)
}

asymmetric_checkerboard_index <- function(X, Y, k, l, resolution1, resolution2) {
    .Call(`_RDM_asymmetric_checkerboard_index`, X, Y, k, l, resolution1, resolution2)
}

